version: "3"
services:
  reverseproxy:
    build:
      context: ./
      dockerfile: Dockerfile
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
      dockerfile: Dockerfile
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed
      dockerfile: Dockerfile
  frontend:
    build:
      context: ../../udacity-c3-frontend
      dockerfile: Dockerfile
