apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: backend-user
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      run: backend-user
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
        - image: adityasanil/udacity-restapi-user
          name: backend-user
          imagePullPolicy: Always
      restartPolicy: Always
