apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: backend-feed
  name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      run: backend-feed
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
        - image: adityasanil/udacity-restapi-feed
          name: backend-feed
          imagePullPolicy: Always
      restartPolicy: Always
